// https://github.com/svg/svgo
module.exports = {
  plugins: [
    { cleanUpEnableBackground: true },
    { cleanupAttrs: true },
    { cleanupIDs: true },
    { cleanupNumericValues: true },
    { collapseGroups: true },
    { convertColors: true },
    { convertPathData: true },
    { convertShapeToPath: true },
    { convertStyleToAttrs: true },
    { convertTransform: true },
    { mergePaths: true },
    { moveElemsAttrsToGroup: true },
    { moveGroupAttrsToElems: true },
    // { removeAttrs: { attrs: '(stroke|fill)' } },
    { removeComments: true },
    { removeDesc: true },
    { removeDimensions: true },
    { removeDoctype: true },
    { removeEditorsNSData: true },
    { removeEmptyAttrs: true },
    { removeEmptyContainers: true },
    { removeEmptyText: true },
    { removeHiddenElems: true },
    { removeMetadata: true },
    { removeNonInheritableGroupAttrs: true },
    { removeRasterImages: false },
    { removeTitle: true },
    { removeUnknownsAndDefaults: true },
    { removeUnusedNS: true },
    { removeUselessDefs: true },
    { removeUselessStrokeAndFill: true },
    { removeViewBox: false },
    { removeXMLProcInst: true },
    { sortAttrs: true },
    { transformsWithOnePath: false },
  ],
}
